### ISSUE TITLE
Ajout d'un bot steam workshop maison

### ISSUE THREAD

**Issue by Alkolique** [mmockelyn/transportfeverfrance#89]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**

**Décrivez la solution que vous souhaitez**
Nous avons actuellement un bot discord qui surveille les nouvelles entrées et mises à jour sur le workshop. Mais ses possiblités sont limités.

L'idéal serait un bot qui regarde les workshop des créateurs, indique les nouvelles publication et les mise à jour des mods avec une certaine mise en forme du message sur discord (titre du mod, taille, auteur et changelog)

**Décrivez les alternatives que vous avez envisagées**

**Comment by mmockelyn** [comment]
Impossible de définir un bot aussi précis dans la demande malgré les recherches effectuer.
Le bot: Workshop Alert est le plus précis à l'heure actuel.
De plus Steam API ne permet pas pour le moment d'effectuer un tel appel
